import React, { useState } from 'react'
import { Check, Plus, X } from 'lucide-react'
import Topbar from '../components/Topbar'
import Modal from '../components/Modal'
import { useData } from '../DataContext'
import { money } from '../utils'

export default function Approvals(){
  const { patients,treatments,priceRequests,requestPrice,decidePrice,patientName,treatmentName } = useData(); const [open,setOpen]=useState(false); const [form,setForm]=useState({patientId:'',treatmentId:'',proposedPrice:'',reason:''})
  const [error,setError]=useState('');const [saving,setSaving]=useState(false);const [deciding,setDeciding]=useState('')
  async function submit(e){e.preventDefault();setSaving(true);setError('');try{await requestPrice(form);setOpen(false);setForm({patientId:'',treatmentId:'',proposedPrice:'',reason:''})}catch(err){setError(err.message||'La demande n’a pas pu être enregistrée.')}finally{setSaving(false)}}
  async function decide(row,status){setDeciding(row.id);setError('');try{await decidePrice(row.id,status)}catch(err){setError(err.message||'La décision n’a pas pu être enregistrée.')}finally{setDeciding('')}}
  return <><Topbar title="Prix négociés" subtitle="Les remises restent sans effet financier jusqu’à approbation administrateur."/><section className="panel"><div className="toolbar"><span className="soft-badge">{priceRequests.filter(x=>x.status==='Pending').length} en attente</span><button className="primary-btn" onClick={()=>{setError('');setOpen(true)}}><Plus size={17}/> Demander une remise</button></div>{error&&!open&&<div className="form-error" role="alert">{error}</div>}<div className="table-wrap"><table><thead><tr><th>Patient</th><th>Soin</th><th>Standard</th><th>Proposé</th><th>Remise</th><th>Statut</th><th>Action</th></tr></thead><tbody>{priceRequests.map(r=><tr key={r.id}><td>{patientName(r.patientId)}</td><td>{treatmentName(r.treatmentId)}</td><td>{money(r.standardPrice)}</td><td><strong>{money(r.proposedPrice)}</strong></td><td>{r.discountPercent}%</td><td><span className={`status ${r.status==='Approved'?'ok':r.status==='Rejected'?'bad':'wait'}`}>{r.status}</span></td><td>{r.status==='Pending'&&<span className="inline-actions"><button className="icon-btn" disabled={deciding===r.id} title="Approuver" onClick={()=>decide(r,'Approved')}><Check size={15}/></button><button className="icon-btn" disabled={deciding===r.id} title="Rejeter" onClick={()=>decide(r,'Rejected')}><X size={15}/></button></span>}</td></tr>)}</tbody></table></div></section><Modal open={open} onClose={()=>setOpen(false)} title="Demander un prix négocié" subtitle="La demande est enregistrée, mais ne modifie pas le prix avant décision."><form onSubmit={submit} className="form-grid"><label>Patient<select required value={form.patientId} onChange={e=>setForm({...form,patientId:e.target.value})}><option value="">Choisir</option>{patients.map(p=><option key={p.id} value={p.id}>{p.firstName} {p.lastName}</option>)}</select></label><label>Soin<select required value={form.treatmentId} onChange={e=>setForm({...form,treatmentId:e.target.value})}><option value="">Choisir</option>{treatments.filter(t=>t.active!==false).map(t=><option key={t.id} value={t.id}>{t.name} · {money(t.price)}</option>)}</select></label><label>Prix proposé (DH)<input required type="number" min="0" step="0.01" value={form.proposedPrice} onChange={e=>setForm({...form,proposedPrice:e.target.value})}/></label><label className="full">Justification<textarea required minLength="4" value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></label>{error&&<div className="form-error full" role="alert">{error}</div>}<div className="form-actions full"><button type="button" className="ghost-btn" onClick={()=>setOpen(false)}>Annuler</button><button className="primary-btn" disabled={saving}>{saving?'Envoi…':'Soumettre la demande'}</button></div></form></Modal></>
}
