import React, { useState } from 'react'
import { Check, Plus, X } from 'lucide-react'
import Topbar from '../components/Topbar'
import Modal from '../components/Modal'
import { useData } from '../DataContext'
import { money, todayISO } from '../utils'

export default function Approvals(){
  const { patients,treatments,treatmentPlans,priceRequests,add,update,patientName,treatmentName,currentUser } = useData(); const [open,setOpen]=useState(false); const [form,setForm]=useState({patientId:'',treatmentId:'',proposedPrice:'',reason:''})
  async function submit(e){e.preventDefault();const t=treatments.find(x=>x.id===form.treatmentId);const plan=treatmentPlans.find(p=>p.patientId===form.patientId&&p.items?.some(i=>i.treatmentId===form.treatmentId));const item=plan?.items.find(i=>i.treatmentId===form.treatmentId);const proposed=Number(form.proposedPrice);if(proposed>=Number(t.price)){alert('Le prix proposé doit être inférieur au prix standard.');return}await add('priceRequests',{patientId:form.patientId,treatmentId:form.treatmentId,planId:plan?.id||'',planItemId:item?.id||'',standardPrice:t.price,proposedPrice:proposed,discountAmount:t.price-proposed,discountPercent:Math.round((1-proposed/t.price)*100),reason:form.reason,requestedBy:currentUser?.id||'u2',requestedAt:todayISO(),status:'Pending'});setOpen(false)}
  async function decide(row,status){if(row.requestedBy===currentUser?.id){alert('Vous ne pouvez pas approuver votre propre demande.');return}await update('priceRequests',row.id,{status,decidedBy:currentUser?.id||'u1',decidedAt:todayISO(),decisionReason:status==='Rejected'?'Prix non validé':'Prix approuvé'});if(status==='Approved'&&row.planId){const plan=treatmentPlans.find(p=>p.id===row.planId);if(plan){const items=plan.items.map(i=>i.id===row.planItemId?{...i,effectivePrice:Number(row.proposedPrice),status:'Approuvé'}:i);await update('treatmentPlans',plan.id,{items,total:items.reduce((s,i)=>s+Number(i.effectivePrice||i.originalPrice||0)*Number(i.quantity||1),0),status:'Accepté',approvedRequestId:row.id})}}}
  return <><Topbar title="Prix négociés" subtitle="Les remises restent sans effet financier jusqu’à approbation administrateur."/><section className="panel"><div className="toolbar"><span className="soft-badge">{priceRequests.filter(x=>x.status==='Pending').length} en attente</span><button className="primary-btn" onClick={()=>setOpen(true)}><Plus size={17}/> Demander une remise</button></div><div className="table-wrap"><table><thead><tr><th>Patient</th><th>Soin</th><th>Standard</th><th>Proposé</th><th>Remise</th><th>Statut</th><th>Action</th></tr></thead><tbody>{priceRequests.map(r=><tr key={r.id}><td>{patientName(r.patientId)}</td><td>{treatmentName(r.treatmentId)}</td><td>{money(r.standardPrice)}</td><td><strong>{money(r.proposedPrice)}</strong></td><td>{r.discountPercent}%</td><td><span className={`status ${r.status==='Approved'?'ok':r.status==='Rejected'?'bad':'wait'}`}>{r.status}</span></td><td>{r.status==='Pending'&&<span className="inline-actions"><button className="icon-btn" title="Approuver" onClick={()=>decide(r,'Approved')}><Check size={15}/></button><button className="icon-btn" title="Rejeter" onClick={()=>decide(r,'Rejected')}><X size={15}/></button></span>}</td></tr>)}</tbody></table></div></section><Modal open={open} onClose={()=>setOpen(false)} title="Demander un prix négocié" subtitle="La demande est enregistrée, mais ne modifie pas le prix avant décision."><form onSubmit={submit} className="form-grid"><label>Patient<select required value={form.patientId} onChange={e=>setForm({...form,patientId:e.target.value})}><option value="">Choisir</option>{patients.map(p=><option key={p.id} value={p.id}>{p.firstName} {p.lastName}</option>)}</select></label><label>Soin<select required value={form.treatmentId} onChange={e=>setForm({...form,treatmentId:e.target.value})}><option value="">Choisir</option>{treatments.filter(t=>t.active!==false).map(t=><option key={t.id} value={t.id}>{t.name} · {money(t.price)}</option>)}</select></label><label>Prix proposé (DH)<input required type="number" min="0" value={form.proposedPrice} onChange={e=>setForm({...form,proposedPrice:e.target.value})}/></label><label className="full">Justification<textarea required value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></label><div className="form-actions full"><button type="button" className="ghost-btn" onClick={()=>setOpen(false)}>Annuler</button><button className="primary-btn">Soumettre la demande</button></div></form></Modal></>
}
