import React, { useMemo, useState } from 'react'
import { Calculator, LockKeyhole, Plus } from 'lucide-react'
import Topbar from '../components/Topbar'
import Modal from '../components/Modal'
import { useData } from '../DataContext'
import { money, todayISO } from '../utils'

export default function CollectionSessions(){
  const { collectionSessions,payments,currentUser,add,update } = useData(); const [open,setOpen]=useState(false); const [counted,setCounted]=useState('')
  const ownSessions=collectionSessions.filter(x=>x.openedBy===currentUser?.id); const visibleSessions=currentUser?.role==='administrator'?collectionSessions:ownSessions; const current=ownSessions.find(x=>x.status==='Open'); const todayPayments=useMemo(()=>payments.filter(p=>current?p.sessionId===current.id:(currentUser?.role==='administrator'&&p.date===todayISO())),[payments,current,currentUser]); const total=todayPayments.reduce((s,p)=>s+Number(p.paid||0),0)
  async function start(e){e.preventDefault();await add('collectionSessions',{openedBy:currentUser?.id||'u2',openedAt:new Date().toISOString(),date:todayISO(),status:'Open',openingCash:Number(e.target.openingCash.value||0)});setOpen(false)}
  async function closeSession(){if(!current)return;await update('collectionSessions',current.id,{status:'Submitted',closedAt:new Date().toISOString(),countedCash:Number(counted||0),recordedTotal:total,discrepancy:Number(counted||0)-total});setCounted('')}
  async function validateSession(id){await update('collectionSessions',id,{status:'Validated',validatedAt:new Date().toISOString(),validatedBy:currentUser?.id})}
  return <><Topbar title="Sessions de caisse" subtitle="Ouvrez, rapprochez et soumettez votre collecte quotidienne."/><div className="report-cards"><div><span>Encaissements suivis</span><strong>{money(total)}</strong></div><div><span>Session active</span><strong>{current?'Ouverte':'Aucune'}</strong></div><div><span>Opérations</span><strong>{todayPayments.length}</strong></div></div><section className="panel"><div className="toolbar"><div><span className="soft-badge"><Calculator size={14}/> {currentUser?.role==='administrator'?'Toutes les sessions':'Session personnelle'}</span></div>{currentUser?.role!=='administrator'&&!current&&<button className="primary-btn" onClick={()=>setOpen(true)}><Plus size={17}/> Ouvrir une session</button>}</div>{current?<div className="session-close"><div><h3>Session ouverte</h3><p>Ouverte le {new Date(current.openedAt).toLocaleString('fr-FR')} · total enregistré {money(total)}</p></div><div className="form-actions"><input className="session-input" type="number" min="0" placeholder="Espèces comptées" value={counted} onChange={e=>setCounted(e.target.value)}/><button className="primary-btn" disabled={counted===''} onClick={closeSession}><LockKeyhole size={15}/> Soumettre la clôture</button></div></div>:currentUser?.role!=='administrator'&&<div className="empty-state">Aucune session ouverte. Ouvrez-en une avant d’enregistrer les prochaines opérations.</div>}<div className="table-wrap"><table><thead><tr><th>Date</th><th>Statut</th><th>Total enregistré</th><th>Espèces comptées</th><th>Écart</th><th>Action</th></tr></thead><tbody>{visibleSessions.slice().reverse().map(s=><tr key={s.id}><td>{s.date}</td><td><span className={`status ${s.status==='Validated'?'ok':'wait'}`}>{s.status}</span></td><td>{money(s.recordedTotal)}</td><td>{money(s.countedCash)}</td><td>{money(s.discrepancy)}</td><td>{currentUser?.role==='administrator'&&s.status==='Submitted'?<button className="ghost-btn" onClick={()=>validateSession(s.id)}>Valider</button>:'—'}</td></tr>)}</tbody></table></div></section><Modal open={open} onClose={()=>setOpen(false)} title="Ouvrir une session" subtitle="Les paiements de la journée seront rapprochés dans cette session."><form onSubmit={start} className="form-grid"><label className="full">Fonds de caisse initial (DH)<input name="openingCash" type="number" min="0" defaultValue="0"/></label><div className="form-actions full"><button type="button" className="ghost-btn" onClick={()=>setOpen(false)}>Annuler</button><button className="primary-btn">Ouvrir</button></div></form></Modal></>
}
