import React, { useEffect, useState } from 'react'
import { ArrowLeft, CalendarClock, Camera, Check, Clipboard, ExternalLink, Mail, MessageCircle, Phone, Plus, Send, UserPlus, UserRound, WalletCards } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import Modal from '../components/Modal'
import Topbar from '../components/Topbar'
import { addLeadInteraction, completeFollowUpTask, convertLeadToPatient, createFollowUpTask, createLeadInvitation, createLeadQuote, getLeadBundle, updateLead, updateLeadQuoteStatus } from '../services/acquisition'

const STAGES=['Nouveau','Contacte','Qualifie','Invitation envoyee','Rendez-vous','Converti','Perdu']

export default function LeadProfile(){
  const {leadId}=useParams();const [bundle,setBundle]=useState(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [interactionOpen,setInteractionOpen]=useState(false);const [inviteOpen,setInviteOpen]=useState(false);const [taskOpen,setTaskOpen]=useState(false);const [quoteOpen,setQuoteOpen]=useState(false);const [busy,setBusy]=useState(false);const [invite,setInvite]=useState(null);const [copied,setCopied]=useState(false);const [convertedPatient,setConvertedPatient]=useState(null)
  const [interaction,setInteraction]=useState({channel:'Telephone',direction:'Sortant',summary:'',outcome:''});const [task,setTask]=useState({title:'Relancer le prospect',dueAt:''});const [quote,setQuote]=useState({title:'Proposition de soins',amount:'',validUntil:'',notes:''})
  async function load(){setLoading(true);try{setBundle(await getLeadBundle(leadId));setError('')}catch(err){setError(err.message||'Impossible de charger ce prospect.')}finally{setLoading(false)}}
  useEffect(()=>{load()},[leadId])
  async function changeLead(patch){setBusy(true);try{const lead=await updateLead(leadId,patch);setBundle(current=>({...current,lead}));setError('')}catch(err){setError(err.message||'Mise à jour impossible.')}finally{setBusy(false)}}
  async function saveInteraction(e){e.preventDefault();setBusy(true);try{const row=await addLeadInteraction(leadId,interaction);setBundle(current=>({...current,lead:{...current.lead,status:'Contacte',lastContactAt:row.createdAt},interactions:[row,...current.interactions]}));setInteractionOpen(false);setInteraction({channel:'Telephone',direction:'Sortant',summary:'',outcome:''})}catch(err){setError(err.message||'Interaction impossible.')}finally{setBusy(false)}}
  async function generateInvite(channel){setBusy(true);try{const created=await createLeadInvitation(leadId,channel);setInvite({...created,url:`${window.location.origin}${created.path}`});setBundle(current=>({...current,lead:{...current.lead,status:'Invitation envoyee'}}))}catch(err){setError(err.message||'Invitation impossible.')}finally{setBusy(false)}}
  async function copyInvite(){await navigator.clipboard.writeText(invite.url);setCopied(true);window.setTimeout(()=>setCopied(false),1800)}
  async function saveTask(e){e.preventDefault();setBusy(true);try{const row=await createFollowUpTask(leadId,task);setBundle(current=>({...current,tasks:[...current.tasks,row]}));setTaskOpen(false);setTask({title:'Relancer le prospect',dueAt:''})}catch(err){setError(err.message||'Relance impossible.')}finally{setBusy(false)}}
  async function finishTask(id){const row=await completeFollowUpTask(id);setBundle(current=>({...current,tasks:current.tasks.map(item=>item.id===id?row:item)}))}
  async function saveQuote(e){e.preventDefault();setBusy(true);try{const row=await createLeadQuote(leadId,quote);setBundle(current=>({...current,quotes:[row,...current.quotes]}));setQuoteOpen(false);setQuote({title:'Proposition de soins',amount:'',validUntil:'',notes:''})}catch(err){setError(err.message||'Devis impossible.')}finally{setBusy(false)}}
  async function changeQuote(id,status){const row=await updateLeadQuoteStatus(id,status);setBundle(current=>({...current,quotes:current.quotes.map(item=>item.id===id?row:item)}))}
  async function convert(){setBusy(true);try{const patient=await convertLeadToPatient(leadId);setConvertedPatient(patient);setBundle(current=>({...current,lead:{...current.lead,status:'Converti'}}))}catch(err){setError(err.message||'Conversion impossible.')}finally{setBusy(false)}}

  if(loading)return <Topbar title="Chargement du prospect…" subtitle="Récupération de la chronologie et des relances."/>
  if(!bundle?.lead)return <><Topbar title="Prospect introuvable" subtitle="Ce dossier n’est pas disponible."/><Link className="ghost-btn profile-back" to="/acquisition"><ArrowLeft size={16}/> Retour à l’acquisition</Link>{error&&<div className="data-error">{error}</div>}</>
  const {lead,interactions,tasks,invitations,media=[],quotes=[]}=bundle
  return <>
    <Topbar title={`${lead.firstName} ${lead.lastName}`} subtitle="Suivi commercial, pré-consultation et prochaine action."/>
    <div className="profile-toolbar"><Link className="ghost-btn" to="/acquisition"><ArrowLeft size={15}/> Pipeline</Link><div>{lead.status==='Converti'&&convertedPatient?<Link className="ghost-btn" to={`/patients/${convertedPatient.patientId}`}><UserRound size={16}/> Ouvrir le patient</Link>:<button className="ghost-btn" disabled={busy} onClick={convert}><UserPlus size={16}/> Convertir en patient</button>}<button className="ghost-btn" onClick={()=>setTaskOpen(true)}><CalendarClock size={16}/> Relance</button><button className="primary-btn" onClick={()=>setInviteOpen(true)}><Send size={16}/> Inviter</button></div></div>
    {error&&<div className="data-error">{error}</div>}
    <section className="panel lead-profile-hero"><div className="profile-identity"><div className="profile-avatar"><UserRound size={25}/></div><div><span className="soft-badge">{lead.source}</span><h2>{lead.firstName} {lead.lastName}</h2><p>{lead.concern||'Besoin à préciser'}</p></div></div><div className="lead-profile-controls"><label>Étape<select value={lead.status} disabled={busy} onChange={e=>changeLead({status:e.target.value})}>{STAGES.map(item=><option key={item}>{item}</option>)}</select></label><label>Priorité<select value={lead.priority} disabled={busy} onChange={e=>changeLead({priority:e.target.value})}><option>Basse</option><option>Normale</option><option>Haute</option><option>Urgente</option></select></label></div><div className="profile-contact"><div><Phone size={16}/><span>{lead.phone||'Téléphone non renseigné'}</span></div><div><Mail size={16}/><span>{lead.email||'Email non renseigné'}</span></div></div></section>
    {media.length>0&&<section className="panel lead-media-panel"><div className="panel-head"><div><h3>Photos de pré-consultation</h3><p>Fichiers privés · liens temporaires d’une heure</p></div><span className="soft-badge"><Camera size={14}/> {media.length} vue(s)</span></div><div className="lead-media-grid">{media.map(item=><article key={item.id}>{item.url?<img src={item.url} alt={item.label}/>:<div className="media-placeholder"><Camera size={22}/></div>}<div><strong>{item.label}</strong><span className="status wait">{item.qualityStatus}</span></div></article>)}</div></section>}
    <div className="lead-detail-grid"><section className="panel"><div className="panel-head"><div><h3>Chronologie</h3><p>Appels, messages et notes de qualification</p></div><button className="ghost-btn" onClick={()=>setInteractionOpen(true)}><Plus size={15}/> Interaction</button></div>{interactions.length?<div className="lead-timeline">{interactions.map(item=><article key={item.id}><div className="timeline-icon">{item.channel==='Telephone'?<Phone size={15}/>:<MessageCircle size={15}/>}</div><div><header><strong>{item.channel} · {item.direction}</strong><time>{new Date(item.createdAt).toLocaleString('fr-FR')}</time></header><p>{item.summary}</p>{item.outcome&&<small>{item.outcome}</small>}</div></article>)}</div>:<div className="empty-state">Aucune interaction. Ajoutez le premier contact.</div>}</section>
      <aside className="lead-side-stack"><section className="panel"><div className="panel-head"><div><h3>Devis</h3><p>Propositions commerciales</p></div><button className="ghost-btn" onClick={()=>setQuoteOpen(true)}><Plus size={15}/> Devis</button></div>{quotes.length?<div className="quote-list">{quotes.map(item=><div key={item.id}><span><strong>{item.title}</strong><small>{Number(item.amount).toLocaleString('fr-FR')} {item.currency}</small></span><select value={item.status} onChange={e=>changeQuote(item.id,e.target.value)}><option>Brouillon</option><option>Envoye</option><option>Accepte</option><option>Refuse</option><option>Expire</option></select></div>)}</div>:<div className="empty-state compact">Aucun devis préparé.</div>}</section><section className="panel"><div className="panel-head"><div><h3>Relances</h3><p>Prochaines actions</p></div></div>{tasks.length?<div className="followup-list">{tasks.map(item=><div key={item.id} className={item.status==='Terminee'?'done':''}><button aria-label="Marquer comme terminée" disabled={item.status==='Terminee'} onClick={()=>finishTask(item.id)}>{item.status==='Terminee'?<Check size={14}/>:null}</button><span><strong>{item.title}</strong><small>{new Date(item.dueAt).toLocaleString('fr-FR')}</small></span></div>)}</div>:<div className="empty-state compact">Aucune relance planifiée.</div>}</section><section className="panel"><div className="panel-head"><div><h3>Invitations</h3><p>Liens de pré-consultation</p></div></div>{invitations.length?<div className="invitation-list">{invitations.map(item=><div key={item.id}><span className={`status ${item.status==='Completee'?'ok':'wait'}`}>{item.status}</span><strong>{item.channel}</strong><small>Expire le {new Date(item.expiresAt).toLocaleDateString('fr-FR')}</small></div>)}</div>:<div className="empty-state compact">Aucune invitation créée.</div>}</section></aside>
    </div>
    <Modal open={interactionOpen} onClose={()=>setInteractionOpen(false)} title="Ajouter une interaction" subtitle="Consignez le contexte et le résultat du contact."><form className="form-grid" onSubmit={saveInteraction}><label>Canal<select value={interaction.channel} onChange={e=>setInteraction({...interaction,channel:e.target.value})}><option>Telephone</option><option>WhatsApp</option><option>Email</option><option>Note</option><option>Visite</option></select></label><label>Direction<select value={interaction.direction} onChange={e=>setInteraction({...interaction,direction:e.target.value})}><option>Sortant</option><option>Entrant</option><option>Interne</option></select></label><label className="full">Résumé<textarea required rows="4" value={interaction.summary} onChange={e=>setInteraction({...interaction,summary:e.target.value})}/></label><label className="full">Résultat <small>(facultatif)</small><input value={interaction.outcome} onChange={e=>setInteraction({...interaction,outcome:e.target.value})}/></label><div className="form-actions full"><button type="button" className="ghost-btn" onClick={()=>setInteractionOpen(false)}>Annuler</button><button className="primary-btn" disabled={busy}>Enregistrer</button></div></form></Modal>
    <Modal open={taskOpen} onClose={()=>setTaskOpen(false)} title="Programmer une relance" subtitle="La tâche apparaîtra dans le dossier du prospect."><form className="form-grid" onSubmit={saveTask}><label className="full">Action<input required value={task.title} onChange={e=>setTask({...task,title:e.target.value})}/></label><label className="full">Échéance<input required type="datetime-local" value={task.dueAt} onChange={e=>setTask({...task,dueAt:e.target.value})}/></label><div className="form-actions full"><button type="button" className="ghost-btn" onClick={()=>setTaskOpen(false)}>Annuler</button><button className="primary-btn" disabled={busy}>Planifier</button></div></form></Modal>
    <Modal open={quoteOpen} onClose={()=>setQuoteOpen(false)} title="Nouveau devis prospect" subtitle="Préparez une estimation avant la conversion en patient."><form className="form-grid" onSubmit={saveQuote}><label className="full">Intitulé<input required value={quote.title} onChange={e=>setQuote({...quote,title:e.target.value})}/></label><label>Montant (MAD)<input required min="0" step="0.01" type="number" value={quote.amount} onChange={e=>setQuote({...quote,amount:e.target.value})}/></label><label>Valide jusqu’au<input type="date" value={quote.validUntil} onChange={e=>setQuote({...quote,validUntil:e.target.value})}/></label><label className="full">Notes<textarea rows="3" value={quote.notes} onChange={e=>setQuote({...quote,notes:e.target.value})}/></label><div className="form-actions full"><button type="button" className="ghost-btn" onClick={()=>setQuoteOpen(false)}>Annuler</button><button className="primary-btn" disabled={busy}><WalletCards size={16}/> Créer le devis</button></div></form></Modal>
    <Modal open={inviteOpen} onClose={()=>{setInviteOpen(false);setInvite(null)}} title="Inviter à la pré-consultation" subtitle="Le lien est personnel, limité dans le temps et ne contient aucune donnée patient.">{invite?<div className="invite-result"><span>Lien prêt à partager</span><div><input readOnly value={invite.url}/><button className="ghost-btn" onClick={copyInvite}>{copied?<Check size={16}/>:<Clipboard size={16}/>} {copied?'Copié':'Copier'}</button></div><Link className="primary-btn full-btn" to={invite.path} target="_blank"><ExternalLink size={16}/> Prévisualiser le formulaire</Link></div>:<div className="invite-channels"><button onClick={()=>generateInvite('Lien')} disabled={busy}><Clipboard size={19}/><strong>Copier un lien</strong><span>À coller dans le canal de votre choix</span></button><button onClick={()=>generateInvite('WhatsApp')} disabled={busy}><MessageCircle size={19}/><strong>WhatsApp</strong><span>Crée le lien prêt à partager</span></button><button onClick={()=>generateInvite('Email')} disabled={busy}><Mail size={19}/><strong>Email</strong><span>Crée le lien prêt à envoyer</span></button></div>}</Modal>
  </>
}
