import React, { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, CalendarRange, Download, RefreshCw } from 'lucide-react'
import Topbar from '../components/Topbar'
import { useData } from '../DataContext'
import { money, todayISO } from '../utils'
import { supabaseEnabled } from '../services/supabase'
import { downloadFinancialCsv, loadFinancialExport, loadFinancialReport } from '../services/reporting'

const isoDaysAgo=days=>{const date=new Date();date.setDate(date.getDate()-days);return date.toISOString().slice(0,10)}
const monthStart=()=>`${todayISO().slice(0,7)}-01`
const blank={summary:{grossCollected:0,corrections:0,netCollected:0,transactionCount:0,averageTransaction:0,outstanding:0,openAccountCount:0},byMethod:[],byTreatment:[],byCollector:[],byDay:[],sessions:[]}
function localReport(payments,sessions,treatments,staff,balances,from,to){const rows=payments.filter(row=>row.date>=from&&row.date<=to);const group=(key,label)=>[...rows.reduce((map,row)=>{const id=key(row);const item=map.get(id)||{id,label:label(id),value:0,count:0};item.value+=Number(row.paid||0);item.count+=1;map.set(id,item);return map},new Map()).values()].sort((a,b)=>b.value-a.value);const paymentsOnly=rows.filter(row=>(row.kind||'payment')==='payment');return {...blank,summary:{grossCollected:paymentsOnly.reduce((sum,row)=>sum+Math.abs(Number(row.paid||0)),0),corrections:Math.abs(rows.filter(row=>(row.kind||'payment')!=='payment').reduce((sum,row)=>sum+Number(row.paid||0),0)),netCollected:rows.reduce((sum,row)=>sum+Number(row.paid||0),0),transactionCount:rows.length,averageTransaction:paymentsOnly.length?paymentsOnly.reduce((sum,row)=>sum+Math.abs(Number(row.paid||0)),0)/paymentsOnly.length:0,outstanding:balances.reduce((sum,row)=>sum+Number(row.remaining||0),0),openAccountCount:balances.filter(row=>Number(row.remaining)>0).length},byMethod:group(row=>row.method||'Autre',id=>id),byTreatment:group(row=>row.treatmentId,id=>treatments.find(item=>item.id===id)?.name||'Soin'),byCollector:group(row=>row.collectorUserId||'Utilisateur',id=>staff.find(item=>item.id===id)?.name||'Utilisateur'),byDay:group(row=>row.date,id=>id).sort((a,b)=>a.id.localeCompare(b.id)),sessions:sessions.filter(row=>row.date>=from&&row.date<=to)}}

export default function Reports(){
  const {payments,collectionSessions,treatments,staff,balances,can}=useData();const [from,setFrom]=useState(monthStart);const [to,setTo]=useState(todayISO);const [report,setReport]=useState(blank);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [exporting,setExporting]=useState(false)
  const fallback=useMemo(()=>localReport(payments,collectionSessions,treatments,staff,balances,from,to),[payments,collectionSessions,treatments,staff,balances,from,to])
  useEffect(()=>{let live=true;setLoading(true);setError('');if(!supabaseEnabled){setReport(fallback);setLoading(false);return()=>{live=false}}loadFinancialReport(from,to).then(data=>{if(live)setReport(data||blank)}).catch(err=>{if(live)setError(err.message||'Rapport indisponible.')}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[from,to,fallback])
  const maxTreatment=Math.max(...report.byTreatment.map(row=>Math.abs(Number(row.value||0))),1);const maxMethod=Math.max(...report.byMethod.map(row=>Math.abs(Number(row.value||0))),1)
  function preset(kind){const end=todayISO();setTo(end);setFrom(kind==='today'?end:kind==='7'?isoDaysAgo(6):kind==='30'?isoDaysAgo(29):monthStart())}
  async function exportCsv(){setExporting(true);setError('');try{if(supabaseEnabled)downloadFinancialCsv(await loadFinancialExport(from,to),from,to);else downloadFinancialCsv(payments.filter(row=>row.date>=from&&row.date<=to).map(row=>({...row,patient:'',treatment:treatments.find(item=>item.id===row.treatmentId)?.name||'Soin',amount:row.paid,collector:staff.find(item=>item.id===row.collectorUserId)?.name||''})),from,to)}catch(err){setError(err.message||'Export impossible.')}finally{setExporting(false)}}
  return <><Topbar title="Rapports" subtitle="Encaissements opérationnels, soldes et rapprochements — distincts du chiffre d’affaires comptable."/>
    <section className="panel report-filter"><div className="report-presets"><button type="button" onClick={()=>preset('today')}>Aujourd’hui</button><button type="button" onClick={()=>preset('7')}>7 jours</button><button type="button" onClick={()=>preset('month')}>Ce mois</button><button type="button" onClick={()=>preset('30')}>30 jours</button></div><div className="report-date-range"><label>Du<input type="date" value={from} max={to} onChange={event=>setFrom(event.target.value)}/></label><label>Au<input type="date" value={to} min={from} max={todayISO()} onChange={event=>setTo(event.target.value)}/></label>{can('reports.export')&&<button type="button" className="ghost-btn" disabled={exporting||loading} onClick={exportCsv}><Download size={16}/>{exporting?'Export…':'Exporter CSV'}</button>}</div></section>
    {error&&<div className="data-error" role="alert"><AlertTriangle size={17}/>{error}</div>}
    {loading?<div className="report-loading"><RefreshCw size={20}/> Calcul du rapport…</div>:<><div className="report-cards report-cards-four"><div><span>Encaissé brut</span><strong>{money(report.summary.grossCollected)}</strong><small>{report.summary.transactionCount} opération(s)</small></div><div><span>Avoirs et corrections</span><strong>{money(report.summary.corrections)}</strong><small>Déduits des encaissements</small></div><div><span>Encaissement net</span><strong>{money(report.summary.netCollected)}</strong><small>Moyenne {money(report.summary.averageTransaction)}</small></div><div><span>Solde à recevoir</span><strong>{money(report.summary.outstanding)}</strong><small>{report.summary.openAccountCount} dossier(s) ouvert(s)</small></div></div>
      <div className="report-grid"><ReportBars title="Encaissements par soin" subtitle="Sommes nettes réellement encaissées" rows={report.byTreatment} max={maxTreatment}/><ReportBars title="Moyens de paiement" subtitle="Répartition nette et volume d’opérations" rows={report.byMethod} max={maxMethod} method/></div>
      <div className="report-grid"><section className="panel"><div className="panel-head"><div><h3>Activité par collecteur</h3><p>Contrôle opérationnel, pas mesure de performance clinique</p></div></div><div className="table-wrap"><table><thead><tr><th>Collaborateur</th><th>Opérations</th><th>Net encaissé</th></tr></thead><tbody>{report.byCollector.map(row=><tr key={row.id||row.label}><td><strong>{row.label}</strong></td><td>{row.count}</td><td>{money(row.value)}</td></tr>)}</tbody></table></div>{!report.byCollector.length&&<div className="empty-state">Aucune activité.</div>}</section><section className="panel"><div className="panel-head"><div><h3>Encaissements par jour</h3><p>Évolution sur la période sélectionnée</p></div><CalendarRange size={19}/></div><div className="report-day-list">{report.byDay.map(row=><div key={row.date||row.id}><span>{row.date||row.id}</span><small>{row.count} opération(s)</small><strong>{money(row.value)}</strong></div>)}</div>{!report.byDay.length&&<div className="empty-state">Aucun encaissement.</div>}</section></div>
      <section className="panel"><div className="panel-head"><div><h3>Rapprochements de caisse</h3><p>Sessions ouvertes, soumises ou validées sur la période</p></div></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Collecteur</th><th>Statut</th><th>Total enregistré</th><th>Espèces attendues</th><th>Espèces comptées</th><th>Écart</th></tr></thead><tbody>{report.sessions.map(row=><tr key={row.id}><td>{row.date}</td><td>{row.collector||'Utilisateur'}</td><td><span className={`status ${row.status==='Validated'?'ok':'wait'}`}>{row.status}</span></td><td>{money(row.recordedTotal)}</td><td>{money(row.recordedCash)}</td><td>{row.countedCash===null||row.countedCash===undefined?'—':money(row.countedCash)}</td><td className={Number(row.discrepancy)!==0?'danger-text':''}>{money(row.discrepancy)}</td></tr>)}</tbody></table></div>{!report.sessions.length&&<div className="empty-state">Aucune session de caisse sur cette période.</div>}</section>
    </>}</>
}

function ReportBars({title,subtitle,rows,max,method=false}){return <section className="panel"><div className="panel-head"><div><h3>{title}</h3><p>{subtitle}</p></div></div>{rows.length?<div className="bar-list">{rows.map(row=><div className="bar-row" key={row.id||row.label}><span>{row.label}{method?` · ${row.count}`:''}</span><div className={`bar-track ${method?'method':''}`}><div style={{width:`${Math.abs(Number(row.value||0))/max*100}%`}}/></div><strong>{money(row.value)}</strong></div>)}</div>:<div className="empty-state">Aucune donnée sur cette période.</div>}</section>}
