import React, { useEffect, useState } from 'react'
import { Armchair, Database, Plus, ShieldCheck } from 'lucide-react'
import Topbar from '../components/Topbar'
import { firebaseEnabled } from '../services/firebase'
import { useData } from '../DataContext'
import { exportLocalData, importLocalData } from '../services/dataStore'
import { supabaseEnabled } from '../services/supabase'
import { listRolePermissions, permissionCatalog, setRolePermission } from '../services/accessControl'

export default function Settings(){
  const { clinic, updateClinic, staff, resources, bookingLinks, add, update, can, currentUser, switchUser } = useData()
  const [draft,setDraft]=useState(clinic)
  const [message,setMessage]=useState('')
  const [roleTab,setRoleTab]=useState('assistant');const [permissions,setPermissions]=useState([]);const [permissionError,setPermissionError]=useState('');const [permissionBusy,setPermissionBusy]=useState('')
  const [resourceDraft,setResourceDraft]=useState({name:'',type:'chair'});const [resourceMessage,setResourceMessage]=useState('');const [resourceBusy,setResourceBusy]=useState('')
  useEffect(()=>{if(!supabaseEnabled)return;listRolePermissions().then(setPermissions).catch(err=>setPermissionError(err.message||'Permissions indisponibles.'))},[])
  async function save(e){e.preventDefault();setMessage('');try{await updateClinic(draft);setMessage('Paramètres enregistrés.')}catch(err){setMessage(err.message||'Enregistrement impossible.')}}
  function exportBackup(){ const blob=new Blob([exportLocalData()],{type:'application/json'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=`dental-spa-backup-${new Date().toISOString().slice(0,10)}.json`; a.click(); URL.revokeObjectURL(url) }
  function importBackup(e){ const file=e.target.files?.[0]; if(!file)return; const reader=new FileReader(); reader.onload=()=>{try{importLocalData(reader.result);alert('Sauvegarde restaurée. La page va être rechargée.');window.location.reload()}catch(err){alert(err.message)}}; reader.readAsText(file); e.target.value='' }
  async function togglePermission(permission,enabled){setPermissionBusy(permission);setPermissionError('');try{await setRolePermission(roleTab,permission,enabled);setPermissions(current=>enabled?[...current.filter(row=>!(row.role===roleTab&&row.permission===permission)),{role:roleTab,permission,scope:'clinic'}]:current.filter(row=>!(row.role===roleTab&&row.permission===permission)))}catch(err){setPermissionError(err.message||'Modification impossible.')}finally{setPermissionBusy('')}}
  async function createResource(e){e.preventDefault();setResourceBusy('new');setResourceMessage('');try{await add('resources',{...resourceDraft,active:true});setResourceDraft({name:'',type:'chair'});setResourceMessage('Ressource ajoutée.')}catch(err){setResourceMessage(err.message||'Ajout impossible.')}finally{setResourceBusy('')}}
  async function toggleResource(resource){
    setResourceMessage('')
    if(resource.active&&resources.filter(row=>row.active).length<=1){setResourceMessage('Au moins une ressource doit rester active.');return}
    setResourceBusy(resource.id);try{
      await update('resources',resource.id,{...resource,active:!resource.active})
      if(resource.active){const replacement=resources.find(row=>row.active&&row.id!==resource.id);for(const link of bookingLinks.filter(row=>row.roomId===resource.id))await update('bookingLinks',link.id,{...link,roomId:replacement.id})}
      setResourceMessage(resource.active?'Ressource désactivée.':'Ressource activée.')
    }catch(err){setResourceMessage(err.message||'Modification impossible.')}finally{setResourceBusy('')}
  }
  async function assignBookingResource(link,roomId){setResourceBusy(`link:${link.id}`);setResourceMessage('');try{await update('bookingLinks',link.id,{...link,roomId});setResourceMessage('Ressource du lien public enregistrée.')}catch(err){setResourceMessage(err.message||'Modification impossible.')}finally{setResourceBusy('')}}
  return <><Topbar title="Paramètres" subtitle="Identité du cabinet et état de la connexion aux données."/>
    <div className="settings-grid"><section className="panel"><div className="panel-head"><div><h3>Cabinet</h3><p>Informations utilisées dans l’interface et les reçus.</p></div></div><form onSubmit={save} className="form-grid"><label className="full">Nom du cabinet<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Téléphone<input value={draft.phone} onChange={e=>setDraft({...draft,phone:e.target.value})}/></label><label>Ville / adresse<input value={draft.address} onChange={e=>setDraft({...draft,address:e.target.value})}/></label><label>Devise<input value={draft.currency} onChange={e=>setDraft({...draft,currency:e.target.value})}/></label><label>Fuseau horaire<input value={draft.timezone} onChange={e=>setDraft({...draft,timezone:e.target.value})}/></label>{message&&<div className="success-strip full">{message}</div>}<div className="form-actions full"><button className="primary-btn">Enregistrer</button></div></form></section>
    <section className="panel"><div className="panel-head"><div><h3>Session de travail</h3><p>Profil opérationnel utilisé pour les permissions du cabinet.</p></div></div>{supabaseEnabled?<div className="current-access-card"><strong>{currentUser?.name||'Utilisateur'}</strong><span>{currentUser?.role||'profil'} · identité liée à Supabase Auth</span></div>:<label className="role-switch">Utilisateur actif<select value={currentUser?.id || ''} onChange={e=>switchUser(e.target.value)}>{staff.map(user=><option key={user.id} value={user.id}>{user.name} · {user.role}</option>)}</select></label>}<div className="security-note"><ShieldCheck size={18}/><p>{supabaseEnabled?'La connexion est assurée par Supabase Auth et les permissions sont chargées depuis la base pour ce compte.':'En production, reliez les rôles à un fournisseur d’authentification avec des règles serveur.'}</p></div></section>
    <section className="panel"><div className="integration-card"><div className={`integration-icon ${supabaseEnabled||firebaseEnabled?'connected':''}`}><Database size={24}/></div><div><h3>Stockage des données</h3><p>{supabaseEnabled?'Supabase distant est actif. Les données sont protégées par authentification et RLS.':firebaseEnabled?'Firebase / Firestore est actif via VITE_USE_FIREBASE=true.':'LocalStorage est actif. Les données restent dans ce navigateur.'}</p><span className={`status ${supabaseEnabled||firebaseEnabled?'ok':'wait'}`}>{supabaseEnabled?'Supabase connecté':firebaseEnabled?'Firebase actif':'Mode local actif'}</span></div></div>{!supabaseEnabled&&<div className="backup-actions"><button type="button" className="ghost-btn" onClick={exportBackup}>Exporter une sauvegarde</button><label className="ghost-btn backup-file">Restaurer une sauvegarde<input type="file" accept="application/json" onChange={importBackup}/></label></div>}<div className="security-note"><ShieldCheck size={18}/><p>{supabaseEnabled?'Les sauvegardes, politiques RLS et comptes utilisateurs sont gérés dans Supabase.':firebaseEnabled?'Vérifiez les règles, Authentication et les sauvegardes avant toute donnée réelle.':'Exportez régulièrement le stockage local.'}</p></div></section></div>
    {can('settings.manage')&&<section className="panel resource-panel"><div className="panel-head"><div><h3>Fauteuils et salles</h3><p>Les conflits sont contrôlés avec le praticien lors de chaque réservation.</p></div><Armchair size={22}/></div><form className="resource-form" onSubmit={createResource}><input required minLength="2" placeholder="Nom de la ressource" value={resourceDraft.name} onChange={e=>setResourceDraft({...resourceDraft,name:e.target.value})}/><select value={resourceDraft.type} onChange={e=>setResourceDraft({...resourceDraft,type:e.target.value})}><option value="chair">Fauteuil</option><option value="room">Salle</option></select><button className="primary-btn" disabled={resourceBusy==='new'}><Plus size={17}/> Ajouter</button></form>{resourceMessage&&<div className="success-strip">{resourceMessage}</div>}<div className="resource-list">{resources.map(resource=><div key={resource.id} className={`resource-row ${resource.active?'':'inactive'}`}><div><strong>{resource.name}</strong><span>{resource.type==='chair'?'Fauteuil':'Salle'} · {resource.active?'Actif':'Inactif'}</span></div><button type="button" className="ghost-btn" disabled={resourceBusy===resource.id} onClick={()=>toggleResource(resource)}>{resource.active?'Désactiver':'Activer'}</button></div>)}</div>{bookingLinks.length>0&&<div className="booking-resource-map"><strong>Liens de réservation publics</strong>{bookingLinks.map(link=><label key={link.id}><span>{link.title||link.slug}</span><select value={link.roomId||''} disabled={resourceBusy===`link:${link.id}`} onChange={e=>assignBookingResource(link,e.target.value)}><option value="">Choisir une ressource</option>{resources.filter(resource=>resource.active).map(resource=><option key={resource.id} value={resource.id}>{resource.name}</option>)}</select></label>)}</div>}</section>}
    {supabaseEnabled&&<section className="panel permission-panel"><div className="panel-head"><div><h3>Rôles et permissions</h3><p>Les changements sont enregistrés dans Supabase et appliqués à la prochaine vérification d’autorisation.</p></div></div><div className="role-tabs"><button className={roleTab==='assistant'?'active':''} onClick={()=>setRoleTab('assistant')}>Assistant / accueil</button><button className={roleTab==='practitioner'?'active':''} onClick={()=>setRoleTab('practitioner')}>Praticien</button></div>{permissionError&&<div className="data-error">{permissionError}</div>}<div className="permission-groups">{permissionCatalog.map(([group,items])=><div key={group}><strong>{group}</strong>{items.map(permission=>{const checked=permissions.some(row=>row.role===roleTab&&row.permission===permission);return <label key={permission}><input type="checkbox" checked={checked} disabled={permissionBusy===permission} onChange={e=>togglePermission(permission,e.target.checked)}/><span>{permission}</span></label>})}</div>)}</div></section>}
  </>
}
