import React, { useState } from 'react'
import { Database, ShieldCheck } from 'lucide-react'
import Topbar from '../components/Topbar'
import { firebaseEnabled } from '../services/firebase'
import { useData } from '../DataContext'
import { exportLocalData, importLocalData } from '../services/dataStore'
import { supabaseEnabled } from '../services/supabase'

export default function Settings(){
  const { clinic, updateClinic, staff, currentUser, switchUser } = useData()
  const [draft,setDraft]=useState(clinic)
  function save(e){e.preventDefault();updateClinic(draft);alert('Paramètres enregistrés')}
  function exportBackup(){ const blob=new Blob([exportLocalData()],{type:'application/json'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=`dental-spa-backup-${new Date().toISOString().slice(0,10)}.json`; a.click(); URL.revokeObjectURL(url) }
  function importBackup(e){ const file=e.target.files?.[0]; if(!file)return; const reader=new FileReader(); reader.onload=()=>{try{importLocalData(reader.result);alert('Sauvegarde restaurée. La page va être rechargée.');window.location.reload()}catch(err){alert(err.message)}}; reader.readAsText(file); e.target.value='' }
  return <><Topbar title="Paramètres" subtitle="Identité du cabinet et état de la connexion aux données."/>
    <div className="settings-grid"><section className="panel"><div className="panel-head"><div><h3>Cabinet</h3><p>Informations utilisées dans l’interface et les reçus.</p></div></div><form onSubmit={save} className="form-grid"><label className="full">Nom du cabinet<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Téléphone<input value={draft.phone} onChange={e=>setDraft({...draft,phone:e.target.value})}/></label><label>Ville / adresse<input value={draft.address} onChange={e=>setDraft({...draft,address:e.target.value})}/></label><label>Devise<input value={draft.currency} onChange={e=>setDraft({...draft,currency:e.target.value})}/></label><label>Fuseau horaire<input value={draft.timezone} onChange={e=>setDraft({...draft,timezone:e.target.value})}/></label><div className="form-actions full"><button className="primary-btn">Enregistrer</button></div></form></section>
    <section className="panel"><div className="panel-head"><div><h3>Session de travail</h3><p>Profil opérationnel utilisé pour les permissions du cabinet.</p></div></div><label className="role-switch">Utilisateur actif<select value={currentUser?.id || ''} onChange={e=>switchUser(e.target.value)}>{staff.map(user=><option key={user.id} value={user.id}>{user.name} · {user.role}</option>)}</select></label><div className="security-note"><ShieldCheck size={18}/><p>{supabaseEnabled?'La connexion est assurée par Supabase Auth et l’accès aux données par les politiques RLS.':'En production, reliez les rôles à un fournisseur d’authentification avec des règles serveur.'}</p></div></section>
    <section className="panel"><div className="integration-card"><div className={`integration-icon ${supabaseEnabled||firebaseEnabled?'connected':''}`}><Database size={24}/></div><div><h3>Stockage des données</h3><p>{supabaseEnabled?'Supabase distant est actif. Les données sont protégées par authentification et RLS.':firebaseEnabled?'Firebase / Firestore est actif via VITE_USE_FIREBASE=true.':'LocalStorage est actif. Les données restent dans ce navigateur.'}</p><span className={`status ${supabaseEnabled||firebaseEnabled?'ok':'wait'}`}>{supabaseEnabled?'Supabase connecté':firebaseEnabled?'Firebase actif':'Mode local actif'}</span></div></div>{!supabaseEnabled&&<div className="backup-actions"><button type="button" className="ghost-btn" onClick={exportBackup}>Exporter une sauvegarde</button><label className="ghost-btn backup-file">Restaurer une sauvegarde<input type="file" accept="application/json" onChange={importBackup}/></label></div>}<div className="security-note"><ShieldCheck size={18}/><p>{supabaseEnabled?'Les sauvegardes, politiques RLS et comptes utilisateurs sont gérés dans Supabase.':firebaseEnabled?'Vérifiez les règles, Authentication et les sauvegardes avant toute donnée réelle.':'Exportez régulièrement le stockage local.'}</p></div></section></div>
  </>
}
