import React, { useState } from 'react'
import { Database, LockKeyhole } from 'lucide-react'
import { useAuth } from '../AuthContext'

export default function AuthGate({children}){
  const {session,loading,ready,error,setupError,bootstrapAvailable,signIn,signUp,resendConfirmation,signOut,supabaseEnabled}=useAuth(); const [mode,setMode]=useState('login'); const [form,setForm]=useState({name:'Administrateur',email:'',password:''}); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('')
  if(!supabaseEnabled) return children
  if(loading||(session&&!ready&&!setupError)) return <main className="auth-page"><div className="auth-card"><Database size={30}/><h1>Préparation du cabinet Supabase…</h1></div></main>
  if(session&&setupError) return <main className="auth-page"><div className="auth-card"><Database size={30}/><h1>Connexion au cabinet impossible</h1><div className="form-error">{setupError}</div><button className="primary-btn large" onClick={signOut}>Se déconnecter</button></div></main>
  if(session&&ready) return children
  async function submit(e){e.preventDefault();setBusy(true);setMessage('');try{const signup=mode==='signup'&&bootstrapAvailable;const data=signup?await signUp(form.name,form.email,form.password):await signIn(form.email,form.password);if(signup&&!data.session)setMessage('Compte créé. Confirmez votre adresse email, puis connectez-vous.')}catch{}finally{setBusy(false)}}
  async function resend(){setBusy(true);setMessage('');try{await resendConfirmation(form.email);setMessage('Email de confirmation renvoyé. Vérifiez aussi les courriers indésirables.')}catch(err){if(err.message?.toLowerCase().includes('rate'))setMessage('Limite d’envoi atteinte. Attendez quelques minutes avant un seul nouvel essai.')}finally{setBusy(false)}}
  return <main className="auth-page"><section className="auth-card"><div className="public-brand"><LockKeyhole size={20}/><span>Dental Spa · Supabase</span></div><h1>{mode==='login'||!bootstrapAvailable?'Connexion au cabinet':'Créer le premier administrateur'}</h1><p>Les données sont stockées dans la base distante et protégées par votre compte.</p><form onSubmit={submit} className="auth-form">{mode==='signup'&&bootstrapAvailable&&<label>Nom<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label>}<label>Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Mot de passe<input required type="password" minLength="8" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>{error&&<div className="form-error">{error}</div>}{message&&<div className="success-strip">{message}</div>}<button disabled={busy} className="primary-btn large">{busy?'Traitement…':mode==='signup'&&bootstrapAvailable?'Créer le compte':'Se connecter'}</button></form>{(mode==='login'||!bootstrapAvailable)&&form.email&&<button disabled={busy} className="auth-switch" onClick={resend}>Renvoyer l’email de confirmation</button>}{bootstrapAvailable&&<button className="auth-switch" onClick={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?'Première utilisation ? Créer le compte administrateur':'Déjà inscrit ? Se connecter'}</button>}</section></main>
}
